configured_endpoints: 24
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/indices/indices-c6502bf2253f16e9aa9cdfd9aec8d77b78c6de4e9c3a7cf646726f999a8ced2c.yml
openapi_spec_hash: 811499d0cffb94af0a9cab7a54d9551f
config_hash: 5811b816ccf8df6d99fdfb80db1f64c8
